### ISSUE TITLE
[메인페이지] 네비게이션

### ISSUE THREAD

**Issue by seohyeonKK** [dnd-side-project/dnd-5th-10-frontend#1]
## 🤷 이슈 내용

메인페이지 상단에 네비게이션 구현

## ✨ 기대 결과

![image](https://user-images.githubusercontent.com/62590535/126252147-05d71ca7-ae1a-4ac0-b0b8-1a0803cfaad3.png)

**Comment by aayusranjan** [comment]
can you tell me in english, would like to help u
